### ISSUE TITLE
getting XSRF errors with latest code

### ISSUE THREAD

**Issue by thehesiod** [google/upvote#15]
```
Traceback (most recent call last):
  File "/base/alloc/tmpfs/dynamic_runtimes/python27/8882c914eb6132e9_unzipped/python27_lib/versions/third_party/webapp2-2.3/webapp2.py", line 1505, in __call__
    rv = self.router.dispatch(request, response)
  File "/base/alloc/tmpfs/dynamic_runtimes/python27/8882c914eb6132e9_unzipped/python27_lib/versions/third_party/webapp2-2.3/webapp2.py", line 1253, in default_dispatcher
    return route.handler_adapter(request, response)
  File "/base/alloc/tmpfs/dynamic_runtimes/python27/8882c914eb6132e9_unzipped/python27_lib/versions/third_party/webapp2-2.3/webapp2.py", line 1077, in __call__
    return handler.dispatch()
  File "/base/data/home/apps/m~santaupvote/santa-api:auto.411437352926953149/upvote/gae/modules/santa_api/sync.py", line 110, in dispatch
    self.abort(httplib.FORBIDDEN, explanation='XSRF token missing/invalid.')
  File "/base/alloc/tmpfs/dynamic_runtimes/python27/8882c914eb6132e9_unzipped/python27_lib/versions/third_party/webapp2-2.3/webapp2.py", line 573, in abort
    abort(code, *args, **kwargs)
  File "/base/alloc/tmpfs/dynamic_runtimes/python27/8882c914eb6132e9_unzipped/python27_lib/versions/third_party/webapp2-2.3/webapp2.py", line 1804, in abort
    raise cls(*args, **kwargs)
HTTPForbidden: XSRF token missing/invalid.
```

**Comment by thehesiod** [comment]
I'm guessing this is normal operation for when santa's token expires.  It would be nice if santa refreshed its token slightly before the expiration time.  I'll look into it

**Comment by ghigliottyc** [comment]
👋 I've also seen this periodically. Do XSRF tokens have an expiry?
