### ISSUE TITLE
unexpected keyword 'overwrite_appengine_config' error while deploying the app to app engine

### ISSUE THREAD

**Issue by rishiv3** [google/upvote#35]
I'm having issues following the steps to deploy

````
+ echo Deploying to App Engine...
Deploying to App Engine...
+ bazel run upvote/gae:monolith_binary.deploy -- rv3-upvote app.yaml santa_api.yaml
INFO: Invocation ID: bbd6d94c-828d-4fa4-97e6-80cad0f54c3c
Loading:
Loading: 0 packages loaded
ERROR: E:/server/upvote/upvote/gae/BUILD:59:1: Traceback (most recent call last):
        File "E:/server/upvote/upvote/gae/BUILD", line 59
                upvote_appengine_test(name = "appengine_config_test", si...", <2 more arguments>)
        File "E:/server/upvote/upvote/builddefs.bzl", line 8, in upvote_appengine_test
                py_appengine_test(name = name, srcs = srcs, deps = dep..., <3 more arguments>)
unexpected keyword 'overwrite_appengine_config' in call to py_appengine_test(name, srcs, deps = [], data = [], libraries = {}, size = None)
ERROR: error loading package 'upvote/gae': Package 'upvote/gae' contains errors
INFO: Elapsed time: 0.402s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded)
ERROR: Build failed. Not running target
FAILED: Build did NOT complete successfully (0 packages loaded)
````

I have tried `overwrite_appengine_config = false,` on `upvote\gae\BUILD`  file but that didnt work.

Any ideas?

Thanks!

**Comment by thehesiod** [comment]
I think this has been fixed, you need to remove the extra setting of `overwrite_appengine_config `, I believe it should only be set once in `upvote_appengine_binary`

**Comment by chief8192** [comment]
I think it's fixed as well, but between the holiday and an internal dependency that was broken until yesterday, I haven't been able to push out a new release. Currently aiming for Tuesday due to the Monday holiday, should be a big delta.

**Comment by thehesiod** [comment]
@chief8192 ah ok, I'll hold off on trying to figure out the packages.json thing then, was about to do bazel deep dive again ;)

**Comment by chief8192** [comment]
Alexander, can you confirm again that this is fixed before I close it out?

**Comment by thehesiod** [comment]
ya personally I didn't have this issue, nor do I since the last merge to master.
