### ISSUE TITLE
missing package.json

### ISSUE THREAD

**Issue by thehesiod** [google/upvote#36]
I think someone forgot to check in this file?

After merging I'm getting:
```
+ bazel run upvote/gae:monolith_binary.deploy -- --project santaupvote --version auto app.yaml santa_api.yaml
INFO: Build options have changed, discarding analysis cache.
ERROR: /Users/amohr/dev/upvote/upvote/gae/modules/upvote_app/frontend/BUILD:77:1: no such package '@npm//ng-html2js/bin': no such package '@nodejs//': Traceback (most recent call last):
	File "/private/var/tmp/_bazel_amohr/13181c36bc3e64d8ab6186cf32fd8fae/external/build_bazel_rules_nodejs/internal/node/node_repositories.bzl", line 418
		_prepare_node(repository_ctx)
	File "/private/var/tmp/_bazel_amohr/13181c36bc3e64d8ab6186cf32fd8fae/external/build_bazel_rules_nodejs/internal/node/node_repositories.bzl", line 325, in _prepare_node
		repository_ctx.file("bin/npm_node_repositories", conte...])), ...)
	File "/private/var/tmp/_bazel_amohr/13181c36bc3e64d8ab6186cf32fd8fae/external/build_bazel_rules_nodejs/internal/node/node_repositories.bzl", line 329, in repository_ctx.file
		"".join(["\necho Running npm \"$@\" in {...])
	File "/private/var/tmp/_bazel_amohr/13181c36bc3e64d8ab6186cf32fd8fae/external/build_bazel_rules_nodejs/internal/node/node_repositories.bzl", line 329, in "".join
		"\necho Running npm \"$@\" in {root}\n(cd \"{root}\"; \"$SCRIPT_DIR/{node}\" \"$SCRIPT_DIR/{script}\" --scripts-prepend-node-path=false \"$@\")\n".format(root = repository_ctx.path(packa..., <2 more arguments>)
	File "/private/var/tmp/_bazel_amohr/13181c36bc3e64d8ab6186cf32fd8fae/external/build_bazel_rules_nodejs/internal/node/node_repositories.bzl", line 333, in "\necho Running npm \"$@\" in {root}\n
		repository_ctx.path(package_json)
Unable to load package for //:package.json: not found. and referenced by '//upvote/gae/modules/upvote_app/frontend:ui_templates_genrule'
ERROR: Analysis of target '//upvote/gae:monolith_binary.deploy' failed; build aborted: no such package '@npm//ng-html2js/bin': no such package '@nodejs//': Traceback (most recent call last):
	File "/private/var/tmp/_bazel_amohr/13181c36bc3e64d8ab6186cf32fd8fae/external/build_bazel_rules_nodejs/internal/node/node_repositories.bzl", line 418
		_prepare_node(repository_ctx)
	File "/private/var/tmp/_bazel_amohr/13181c36bc3e64d8ab6186cf32fd8fae/external/build_bazel_rules_nodejs/internal/node/node_repositories.bzl", line 325, in _prepare_node
		repository_ctx.file("bin/npm_node_repositories", conte...])), ...)
	File "/private/var/tmp/_bazel_amohr/13181c36bc3e64d8ab6186cf32fd8fae/external/build_bazel_rules_nodejs/internal/node/node_repositories.bzl", line 329, in repository_ctx.file
		"".join(["\necho Running npm \"$@\" in {...])
	File "/private/var/tmp/_bazel_amohr/13181c36bc3e64d8ab6186cf32fd8fae/external/build_bazel_rules_nodejs/internal/node/node_repositories.bzl", line 329, in "".join
		"\necho Running npm \"$@\" in {root}\n(cd \"{root}\"; \"$SCRIPT_DIR/{node}\" \"$SCRIPT_DIR/{script}\" --scripts-prepend-node-path=false \"$@\")\n".format(root = repository_ctx.path(packa..., <2 more arguments>)
	File "/private/var/tmp/_bazel_amohr/13181c36bc3e64d8ab6186cf32fd8fae/external/build_bazel_rules_nodejs/internal/node/node_repositories.bzl", line 333, in "\necho Running npm \"$@\" in {root}\n
		repository_ctx.path(package_json)

```

**Comment by thehesiod** [comment]
I'm not sure why google devs are checking in builds that are failing, last commit yielded: https://travis-ci.com/google/upvote/jobs/164954503

**Comment by chief8192** [comment]
Currently it's just "dev", singular. I'm doing the best I can to ensure that the public release is staying in proper working order, but sometimes stuff slips through the cracks.
