### ISSUE TITLE
Setting Failsafe_Administrators Produces a Traceback Error

### ISSUE THREAD

**Issue by gmarnin** [google/upvote#5]
To reproduce:

1. Set an email address for `FAILSAFE_ADMINISTRATORS` in `/upvote/gae/shared/common/settings.py` and saved the file. 

2. Run `bazel run upvote/gae:monolith_binary.deploy -- ${PROJ_ID}` which shows no errors. 

3. Manually triggered the cron from the Cloud Console's cron page Which failed.

4. Opened `https://<my-app>.appspot.com/admin/settings` which shows the traceback:

```Traceback (most recent call last):
  File "/base/alloc/tmpfs/dynamic_runtimes/python27/6baee03590d046f1_unzipped/python27_lib/versions/1/google/appengine/runtime/wsgi.py", line 240, in Handle
    handler = _config_handle.add_wsgi_middleware(self._LoadHandler())
  File "/base/alloc/tmpfs/dynamic_runtimes/python27/6baee03590d046f1_unzipped/python27_lib/versions/1/google/appengine/api/lib_config.py", line 351, in __getattr__
    self._update_configs()
  File "/base/alloc/tmpfs/dynamic_runtimes/python27/6baee03590d046f1_unzipped/python27_lib/versions/1/google/appengine/api/lib_config.py", line 287, in _update_configs
    self._registry.initialize()
  File "/base/alloc/tmpfs/dynamic_runtimes/python27/6baee03590d046f1_unzipped/python27_lib/versions/1/google/appengine/api/lib_config.py", line 160, in initialize
    import_func(self._modname)
  File "/base/data/home/apps/d~its-upvote/auto.408675188517060759/appengine_config.py", line 10, in <module>
    import upvote.gae.real_appengine_config
  File "/base/data/home/apps/d~its-upvote/auto.408675188517060759/upvote/gae/real_appengine_config.py", line 20, in <module>
    from upvote.gae import appengine_config_utils
  File "/base/data/home/apps/d~its-upvote/auto.408675188517060759/upvote/gae/appengine_config_utils.py", line 20, in <module>
    from upvote.gae.datastore import test_utils
  File "/base/data/home/apps/d~its-upvote/auto.408675188517060759/upvote/gae/datastore/test_utils.py", line 26, in <module>
    from upvote.gae.datastore.models import base
  File "/base/data/home/apps/d~its-upvote/auto.408675188517060759/upvote/gae/datastore/models/base.py", line 29, in <module>
    from upvote.gae.datastore.models import bigquery
  File "/base/data/home/apps/d~its-upvote/auto.408675188517060759/upvote/gae/datastore/models/bigquery.py", line 22, in <module>
    from upvote.gae.shared.common import settings
  File "/base/data/home/apps/d~its-upvote/auto.408675188517060759/upvote/gae/shared/common/settings.py", line 72
    FAILSAFE_ADMINISTRATORS = [itstest_upvote@gmail.com]
                                             ^
SyntaxError: invalid syntax
```

5. Leaving `FAILSAFE_ADMINISTRATORS` blank and rerunning steps 2, 3, and 4 result in successful access to the admin site.

**Comment by clburlison** [comment]
@gmarnin the email address needs to be inside of quotes.

**Comment by msuozzo** [comment]
Yep, what @clburlison said. The settings file needs to conform to normal Python syntax rules.

Thanks for the report!
