### ISSUE TITLE
Error Running init_project.sh

### ISSUE THREAD

**Issue by greaterfool** [google/upvote#59]
```
$ ./init_project.sh 

Initializing Upvote for GCP project: "white-feat-249718"
+ gcloud config set project white-feat-249718
Updated property [core/project].
+ echo Enabling App Engine...
Enabling App Engine...
++ gcloud app describe '--format=value(id)'
+ [[ '' != \w\h\i\t\e\-\f\e\a\t\-\2\4\9\7\1\8 ]]
+ gcloud app create
You are creating an app for project [white-feat-249718].
WARNING: Creating an App Engine application for a project is irreversible and the region
cannot be changed. More information about regions is at
<https://cloud.google.com/appengine/docs/locations>.

[ Snip ]

Creating App Engine application in project [white-feat-249718] and region [us-central]....done.                                                                                           
Success! The app is now created. Please use `gcloud app deploy` to deploy your first app.
+ echo Enabling APIs used by Upvote...
Enabling APIs used by Upvote...
+ gcloud services enable cloudkms.googleapis.com
Operation "operations/acf.fac977e7-0f57-45e4-8327-ca1329fd2b06" finished successfully.
+ gcloud services enable bigquery-json.googleapis.com
+ echo Creating encryption keys used to store Upvote API secrets...
Creating encryption keys used to store Upvote API secrets...
+ gcloud kms keyrings create ring --location=global
+ gcloud kms keys create virustotal --purpose=encryption --keyring=ring --location=global
+ echo Granting necessary permissions to App Engine...
Granting necessary permissions to App Engine...
++ gcloud iam service-accounts list '--filter=App Engine app default service account' '--format=value(email)'
+ SERVICE_ACCOUNT=white-feat-249718@appspot.gserviceaccount.com
+ gcloud projects add-iam-policy-binding white-feat-249718 --member serviceAccount:white-feat-249718@appspot.gserviceaccount.com --role roles/cloudkms.cryptoKeyEncrypterDecrypter
Updated IAM policy for project [white-feat-249718].
bindings:
- members:
  - serviceAccount:white-feat-249718@appspot.gserviceaccount.com
  role: roles/cloudkms.cryptoKeyEncrypterDecrypter
- members:
  - serviceAccount:white-feat-249718@appspot.gserviceaccount.com
  role: roles/editor
- members:
  - user:india.tango@patientpop.com
  - user:summit.hainey@patientpop.com
  role: roles/owner
etag: BwWQBBec2ao=
version: 1
+ echo Configuring App Engine...
Configuring App Engine...
+ ./manage_crons.py disable_all
+ echo Deploying temporary default version to App Engine...
Deploying temporary default version to App Engine...
+ bazel run upvote/gae:monolith_binary.deploy -- white-feat-249718 app.yaml
+ echo

+ echo Deploying to App Engine...
Deploying to App Engine...
+ bazel run upvote/gae:monolith_binary.deploy -- white-feat-249718 app.yaml
INFO: Call stack for the definition of repository 'remotejdk11_macos' which is a http_archive (rule definition at /private/var/tmp/_bazel_summit.hainey/f4e5186114806b0b8302ec418f57ad1d/external/bazel_tools/tools/build_defs/repo/http.bzl:237:16):
 - /DEFAULT.WORKSPACE.SUFFIX:219:1
ERROR: /private/var/tmp/_bazel_summit.hainey/f4e5186114806b0b8302ec418f57ad1d/external/com_google_protobuf/protobuf.bzl:130:19: Traceback (most recent call last):        File "/private/var/tmp/_bazel_summit.hainey/f4e5186114806b0b8302ec418f57ad1d/external/com_google_protobuf/protobuf.bzl", line 125
                rule(attrs = {"srcs": attr.label_list...()}, <2 more arguments>)
        File "/private/var/tmp/_bazel_summit.hainey/f4e5186114806b0b8302ec418f57ad1d/external/com_google_protobuf/protobuf.bzl", line 130, in rule
                attr.label(cfg = "host", executable = True, sin..., ...)
'single_file' is no longer supported. use allow_single_file instead. You can use --incompatible_disable_deprecated_attr_params=false to temporarily disable this check.
ERROR: /private/var/tmp/_bazel_summit.hainey/f4e5186114806b0b8302ec418f57ad1d/external/com_google_javascript_closure_compiler/BUILD:7:1: error loading package '@com_google_protobuf//': Ex
tension file 'protobuf.bzl' has errors and referenced by '@com_google_javascript_closure_compiler//:com_google_javascript_closure_compiler'
ERROR: Analysis of target '//upvote/gae:monolith_binary.deploy' failed; build aborted: error loading package '@com_google_protobuf//': Extension file 'protobuf.bzl' has errors
INFO: Elapsed time: 2.280s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded, 0 targets configured)
FAILED: Build did NOT complete successfully (0 packages loaded, 0 targets configured)
    currently loading: @com_google_protobuf//
    Fetching @gcloud_auth_httplib2_git; Cloning 136da2cd50aa7deb769062cf1d77259d64743a7f of https://github.com/GoogleCloudPlatform/google-auth-library-python-httplib2.git
```

**Comment by greaterfool** [comment]
Resolved this temporarily by rolling back to Bazel v 0.26.0
